name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"
  ITEM:
      description: "who"
      required: true
      defalt: "Yanusi"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "clock"
  color: "grenn"
